# Project information
site_name: Anonipy
site_author: Erik Novak
site_description: >-
  Data anonymization package, supporting different anonymization strategies

# Repository
repo_name: eriknovak/anonipy
repo_url: https://github.com/eriknovak/anonipy

# Configuration
theme:
  name: material
  features:
    - content.code.copy
    - content.code.annotate
    - content.tooltips
    - navigation.indexes
    - navigation.tabs
    - navigation.top
    - navigation.footer
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  palette:
    # Palette toggle for light
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      accent: blue
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    # Palette toggle for dark
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: blue
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  logo: assets/imgs/logo.png
  favicon: assets/imgs/favicon.png

edit_uri: ""

extra_css:
  - css/extra.css

# Plugins
plugins:
  - blog
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - mkdocs-jupyter:
      include: ["*.ipynb"]
  - mkdocstrings:
      handlers:
        python:
          options:
            show_root_heading: False
            show_root_toc_entry: False
            members_order: "source"
            heading_level: 4

# Markdown Extensions
markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji

# Page tree
nav:
  - Home: index.md

  - How-To Guides:
    - Overview: how-to-guides/notebooks/00-overview.ipynb
    - Extractors: how-to-guides/notebooks/01-extractors.ipynb
    - Generators: how-to-guides/notebooks/02-generators.ipynb
    - Strategies: how-to-guides/notebooks/03-strategies.ipynb
    - Utility: how-to-guides/notebooks/04-utility.ipynb
  - API Reference:
    - references/index.md
    - anonymize:
      - references/anonymize/index.md
      - extractors: references/anonymize/extractors.md
      - generators: references/anonymize/generators.md
      - strategies: references/anonymize/strategies.md
    - utils:
      - references/utils/index.md
      - file_system: references/utils/file_system.md
      - language_detector: references/utils/language_detector.md
    - definitions: references/definitions.md
    - constants: references/constants.md

  - Blog:
    - blog/index.md

  - Changelog: changelog.md
  - Development: development.md